apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jtbaba-eks-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    volumeSize: 40
    volumeType: gp2
    tags:
      nodegroup-type: worker

 
